### ISSUE TITLE
HELP

### ISSUE THREAD

**Issue by Squidtito** [Leather128/FNF-SDL#1]
your mom

**Comment by Leather128** [comment]
oh my god how did you find this so quick wtffff

**Comment by Squidtito** [comment]
I may or may not be in your vc

**Comment by Squidtito** [comment]
I don't know... I'll give you a hint, yellow

**Comment by Leather128** [comment]
ok

**Comment by Squidtito** [comment]
You know who I am??

**Comment by Squidtito** [comment]
Listen here yellow man, I am very powerful. As I have a twitter account with 20,000 followers, if you times my current follow count my 1000..

**Comment by Leather128** [comment]
ok
